env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier
parser: '@typescript-eslint/parser'
overrides: []
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 'latest'
  sourceType: 'module'
plugins:
  - import
rules:
  import/order:
    - 'error'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - - 'parent'
          - 'sibling'
        - 'object'
        - 'type'
        - 'index'
